#!/usr/bin/env python

# Usage: refseq_parser -i <reports> --taxid <taxonomic ID>

import sys
import csv
import gzip
import argparse as ap
from ete3 import NCBITaxa

parser = ap.ArgumentParser(prog='outlier-parser', conflict_handler='resolve',
                           description="Parses output file to eliminate outliers")


input = parser.add_argument_group('Input', '')
input.add_argument('-i', '--input', nargs='+', required=True, help="Tab-delimited RefSeq Masher reports")
input.add_argument('--taxid', metavar="INT", required=True, help='Target taxonomic ID')

if len(sys.argv) == 1:
    parser.print_usage()
    sys.exit(1)

args = parser.parse_args()

"""Determining organism"""
try:
    meta = gzip.open(args.reference, 'rb').readline().split()
except:
    meta = open(args.reference, 'rb').readline().split()
organism = "%s %s" % (meta[1].decode('utf-8'), meta[2].decode('utf-8'))

output = open("outlier_list.txt", "w")
outlier_flag = False
accession = ""

ncbi = NCBITaxa()
descendants = ncbi.get_descendant_taxa(args.taxid, intermediate_nodes=True)

for report in args.input: 
    with open(report) as csvfile:
        reader = csv.DictReader(csvfile, delimiter='\t')
        next(reader, None)

        for row in reader:
            if row['sample'] == accession and outlier_flag:
                continue
            accession = row['sample']

            if (int(row['taxid']) != int(args.taxid) and int(row['taxid']) not in descendants) or float(row['distance']) > 0.05:
                output.write("%s\n" % accession)
                outlier_flag = True
