package:
  name: ngsweep
  version: "0.0.1"

source:
  path: ../

requirements:
  host:
    - python >=2.7
    - setuptools

  run:
    - python
    - refseq_masher >=0.1.1
    - multiqc >=1.6a0
    - samtools >=1.8
    - trim-galore >=0.5.0
    - smalt >=0.7.6
    - bwa >=0.7.17
    - kraken >=1.1
    - ete3 >=3.1.1
    - mpi4py >=3.0.0

test:
  commands:
    - ngsweep --help
    - ngsweep --test

about:
  home: https://github.com/WGS-TB/NGSweep
  summary: Next-Gen Sequencing Data Preprocessing Pipeline
  license: GPL-3.0
  license_file: LICENSE